name: Fetch GitHub Repo Info

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch repo data
        run: |
          echo "Fetching repo info..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -o docs/repo_info.json \
               "https://api.github.com/repos/Gruncan/donnchadh"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/repo_info.json  # Stage the file from the /docs folder
          git commit -m "Update repo info"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
